### ISSUE TITLE
[1.10] Vivecraft Installer crashes when clicking change directory button

### ISSUE THREAD

**Issue by f03n1x** [jrbudda/Vivecraft_110#109]
I don't have the Minecraft Launcher open, nor do I have anything specific to Minecraft open at all, but I wanted to change the directory for where Vivecraft is installed, from it's default appdata\roaming\.minecraft directory to the same directory where twitch installed Minecraft but cannot do so. When I click the "..." i.e. the change directory button the launcher closes or more likely some sort of exception is thrown and not caught. This happens with the Mod pack Directory button as well.

I'll also add in any error logs that popup if someone could tell me how I can specifically find that out for the installer (even if it was just logging the errors in command prompt).

Steps to reproduce:
1. Download the 1.10 Vivecraft installer
2. Open installer and click the change directory button for either the installed path or Mod pack directory
3. Vivecraft installer crashes/closes

**Comment by Techjar** [comment]
First of all, make sure your Java version is 8u152 or newer, as that was a compatibility issue with the Windows 10 creators update that was fixed in that version. Second, you shouldn't be changing the install directory unless you're using MultiMC, only change the game directory to where your mod pack is installed. Pointing the install directory at the twitch launcher will not work, Vivecraft is only compatible with the vanilla launcher and MultiMC, for technical reasons.

**Comment by f03n1x** [comment]
Updating java worked no issues.

**Comment by Techjar** [comment]
Awesome.
