### ISSUE TITLE
[Discussion] Forge Support for 1.10

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/Vivecraft_110#35]
There are, as I see it, 3 ways to go about it.

Option 1) Reflection

Pros:
- Single codebase for forge/nonforge
- Can use 1.7.10 as example

Cons:
- Impediment to modifying vanilla files
- Performance due to reflection?

Option 2) Modify Forge Base

Pros:
- Can use existing vanilla patches as basis.

Cons:
- Unknown how to include optifine
- Have to distribute full Forge source?
- Separate codebase from vanilla vivecraft.

Option 3) Forge Mod

Pros:
- Does not require installation

Cons:
- ASM. ASM. ASM. 
- Lose ability to edit classloader.
- Separate codebase from vanilla vivecraft.

**Comment by Thieri85** [comment]
Hi,

honestly i don't exactly understand the options listed above (sorry i'm not native english speaking).

But short question: is it planned to bring vivecraft for 1.10.2 with forge support?
i think vivecraft runs a lot smoother with 1.10.2 but vanilla lacks a lot of nice stuff from the mods.

Nice Regards,
Thieri85

**Comment by Chicachu** [comment]
It looks like vivecraft hasn't been worked on since late August (I'm hoping that it just means something really big is in the works ;) but I wont get my hopes up). Is forge support for 1.10.2 still in the works at all or has vivecraft been abandoned? I would gladly offer donations to keep this mod alive. I just recently bought a vive and this will be my only method of being able to play on my minecraft server with my friends. Still haven't been able to get it to launch yet but I just saw the resolved issue - will try the firewall thing. 

Cheers to all the hard work put in already and if it has been put aside for more important things I still appreciate all of the work that has been put in so far.

**Comment by ThomasRules2000** [comment]
(Bump!) In regards to option 2, I don't think you'd have to redistribute the whole forge source, just the classes you changed. You should just be able to write something that causes a prompt for the user to download optifine if it's not detected as a forge mod too.

**Comment by kevhawk2914** [comment]
You don't have to distribute the forge source at all. Everything you want to accomplish could be done through the use of Mixins. All of this could be done with a forge mod, and possibly a server side mod for players to be able to play on public servers.

https://github.com/SpongePowered/Mixin

**Comment by jrbudda** [comment]
Woo!
